using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class AddIdempotencyKeys : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Additive and idempotent: only a new table and its indexes, created IF NOT EXISTS - re-running it, or running it
            // where they already exist, changes nothing, and no existing row of any other table is touched.
            migrationBuilder.Sql(@"
CREATE TABLE IF NOT EXISTS ""IdempotencyKeys"" (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
    ""Key"" character varying(100) NOT NULL,
    ""UserId"" integer NOT NULL,
    ""RequestHash"" character varying(64) NOT NULL,
    ""ResponseStatus"" integer NOT NULL,
    ""ResponseBody"" text NULL,
    ""CreatedAt"" timestamp with time zone NOT NULL,
    CONSTRAINT ""PK_IdempotencyKeys"" PRIMARY KEY (""Id""),
    CONSTRAINT ""FK_IdempotencyKeys_Users_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""Users"" (""Id"") ON DELETE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS ""IX_IdempotencyKeys_UserId_Key"" ON ""IdempotencyKeys"" (""UserId"", ""Key"");
CREATE INDEX IF NOT EXISTS ""IX_IdempotencyKeys_CreatedAt"" ON ""IdempotencyKeys"" (""CreatedAt"");
");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("DROP TABLE IF EXISTS \"IdempotencyKeys\";");
        }
    }
}
