using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class AddFinance : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Additive and idempotent: two new tables with their indexes (IF NOT EXISTS), then a backfill that can only add
            // missing incomes (ON CONFLICT DO NOTHING). No existing row of Orders, OrderItems, Reviews or any other table is
            // changed, and re-running it, or running it where the tables exist, changes nothing.
            migrationBuilder.Sql(@"
CREATE TABLE IF NOT EXISTS ""Payments"" (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
    ""OrderId"" integer NOT NULL,
    ""Type"" integer NOT NULL,
    ""Amount"" numeric(18,2) NOT NULL,
    ""CreatedAt"" timestamp with time zone NOT NULL,
    CONSTRAINT ""PK_Payments"" PRIMARY KEY (""Id""),
    CONSTRAINT ""CK_Payments_Amount_Positive"" CHECK (""Amount"" > 0),
    CONSTRAINT ""FK_Payments_Orders_OrderId"" FOREIGN KEY (""OrderId"") REFERENCES ""Orders"" (""Id"") ON DELETE RESTRICT
);
CREATE UNIQUE INDEX IF NOT EXISTS ""IX_Payments_OrderId_Type"" ON ""Payments"" (""OrderId"", ""Type"");
CREATE INDEX IF NOT EXISTS ""IX_Payments_CreatedAt"" ON ""Payments"" (""CreatedAt"");

CREATE TABLE IF NOT EXISTS ""Expenses"" (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
    ""Category"" integer NOT NULL,
    ""Amount"" numeric(18,2) NOT NULL,
    ""ExpenseDate"" timestamp with time zone NOT NULL,
    ""Comment"" character varying(500) NULL,
    ""CreatedByUserId"" integer NOT NULL,
    ""CreatedAt"" timestamp with time zone NOT NULL,
    CONSTRAINT ""PK_Expenses"" PRIMARY KEY (""Id""),
    CONSTRAINT ""CK_Expenses_Amount_Positive"" CHECK (""Amount"" > 0),
    CONSTRAINT ""FK_Expenses_Users_CreatedByUserId"" FOREIGN KEY (""CreatedByUserId"") REFERENCES ""Users"" (""Id"") ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS ""IX_Expenses_CreatedByUserId"" ON ""Expenses"" (""CreatedByUserId"");
CREATE INDEX IF NOT EXISTS ""IX_Expenses_ExpenseDate"" ON ""Expenses"" (""ExpenseDate"");
");

            // Income for every order that is already Delivered (see PaymentBackfill for the rules).
            migrationBuilder.Sql(PaymentBackfill.Sql);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("DROP TABLE IF EXISTS \"Payments\"; DROP TABLE IF EXISTS \"Expenses\";");
        }
    }
}
